name: FTP Deploy

on:
  push:
    branches:
      - main # 또는 사용하는 브랜치 이름

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: FTP Deploy to Dothome
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./포트폴리오 2025/
          server-dir: /html/portfolio/
          dangerous-clean-slate: false
